version: "3.3"
services:
    backend:
        build:
            context: ./backend
            dockerfile: Dockerfile_prod
        ports:
            - "0.0.0.0:3000:3000"
        environment:
            LD_LIBRARY_PATH: "/opt/oracle/instantclient_19_10"
            WALLET: "/app/oracle/wallet"
            BACKEND_PORT: "3000"
        volumes:
            - "./backend:/app"
            - "/app/node_modules"
            - "/var/run/docker.sock:/var/run/docker.sock"
            - "./backend/oracle/wallet:/opt/oracle/instantclient_19_10/network/admin"
        image: backend:latest
        links:
            - redis
        container_name: reddit_backend_prod
    redis:
        restart: always
        container_name: reddit_redis
        image: redis:alpine
        ports:
            - "127.0.0.1:6380:6379"