module.exports.THREAD = "THREAD";
module.exports.THREAD_STAT = "THREAD_STAT";
module.exports.USERS = "USERS";

module.exports.CACHE_PUBLIC_TREND="CACHE_TREND"
module.exports.CACHE_PUBLIC_VOTE="CACHE_VOTE"
module.exports.CACHE_PUBLIC_COMMENT="CACHE_COMMENT"

module.exports.CACHE_THREAD="CACHE_THREAD"
module.exports.CACHE_THREAD_STAT="CACHE_THREAD_STAT"

module.exports.CACHE_COUNT_FORUM="CACHE_COUNT_FORUM"
module.exports.CACHE_COUNT_UPDATE="CACHE_COUNT_UPDATE"
module.exports.CACHE_COUNT_POST="CACHE_COUNT_POST"
module.exports.CACHE_COUNT_TREND="CACHE_COUNT_TREND"